project:
  type: website
  resources:
    - assets/**

website:
  title: "Dr. D's Data Science"
  site-url: https://drddatascience.com
  description: "Public Safety Data Science by Dr. Tony Dunsworth"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Resume
        href: resume.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/trdunsworth
      - icon: medium
        href: https://medium.com/@trdunsworth

# Support for multiple engines
execute:
  keep-md: true
  
# Enable acronyms site-wide and load shared definitions
filters: [acronyms]
acronyms:
  # Centralized acronyms list (YAML). You can also supply a list of files.
  fromfile: acronyms.yml
  # Default rendering style for first/next uses
  style: long-short
  # Where to insert the List of Acronyms automatically (or set to false)
  insert_loa: false
  
format:
  html:
    theme: yeti
    css: styles.css
    
comments:
  giscus:
    repo: trdunsworth/drddatascience
